channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5
  - pip=20.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      #- rpaframework==12.9.0 # https://rpaframework.org/releasenotes.html
      - rpaframework==14.1.1
      - robotframework==5.0a1     
      - robotframework-imaplibrary==0.3.0
      - rpaframework-windows==2.0.0
      - rpaframework-recognition==4.0.0
      - keyring==23.5.1
      - azure==4.0.0
      - azure-identity==1.10.0
      - azure-keyvault==1.1.0
      - azure-keyvault-secrets==4.4.0
      - mysql-connector==2.2.9
      - mysql-connector-python==8.0.30